// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDR2FHEZepmouskXWys4H9GtPFMBSmIh9I',
    appId: '1:399199818874:web:2cb9aeca97b94ec88057c3',
    messagingSenderId: '399199818874',
    projectId: 'sharethemeal-d8714',
    authDomain: 'sharethemeal-d8714.firebaseapp.com',
    storageBucket: 'sharethemeal-d8714.firebasestorage.app',
    measurementId: 'G-S3EQW27M1V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7vnyeZl90wX4869FNiX_N6_AQWZUlufQ',
    appId: '1:399199818874:android:d8d947e5a060c84f8057c3',
    messagingSenderId: '399199818874',
    projectId: 'sharethemeal-d8714',
    storageBucket: 'sharethemeal-d8714.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUGqqDsiSfilNAEENyjpXljNspP0vlo6s',
    appId: '1:399199818874:ios:2e24ec440ff630b28057c3',
    messagingSenderId: '399199818874',
    projectId: 'sharethemeal-d8714',
    storageBucket: 'sharethemeal-d8714.firebasestorage.app',
    iosBundleId: 'com.example.shareTheMealApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDR2FHEZepmouskXWys4H9GtPFMBSmIh9I',
    appId: '1:399199818874:web:2b404f3d330f222c8057c3',
    messagingSenderId: '399199818874',
    projectId: 'sharethemeal-d8714',
    authDomain: 'sharethemeal-d8714.firebaseapp.com',
    storageBucket: 'sharethemeal-d8714.firebasestorage.app',
    measurementId: 'G-NTBZFWJ1DF',
  );
}
